# Generated by Django 4.1.7 on 2023-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_category_id_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_book',
            field=models.BooleanField(default=False),
        ),
    ]
